[project]
authors = ["Henrik Kvamme <henrik@kvamme.xyz>"]
entry = "./main.sw"
license = "Apache-2.0"
name = "pig"

[dependencies]
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.20.1" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.4.1" }
